/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Emprestimos.Telas;

import Emprestimos.VO.EmprestimoVO;
import Emprestimos.VO.ItemVO;
import Emprestimos.VO.LoginVO;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lennonalves
 */
public class TelaEmprestimos extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    
    public static TelaEmprestimos instancia;
    
    protected TelaEmprestimos() {
        initComponents();
        this.setLocationRelativeTo(null);
        evo.tableIds = (DefaultTableModel) tbIds.getModel();
        evo.tableItens = (DefaultTableModel) tbItens.getModel();
    }
    
    public static TelaEmprestimos getInstancia() {
        if (instancia == null)
            instancia = new TelaEmprestimos();
        return instancia;
    }
    
    LoginVO lvo = LoginVO.getInstancia();
    EmprestimoVO evo = EmprestimoVO.getInstancia();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloPagina = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItens = new javax.swing.JTable();
        btnEmprestar = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        btnEmprestados = new javax.swing.JButton();
        btnDisponiveis = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbIds = new javax.swing.JTable();
        btnMostrar = new javax.swing.JButton();
        lblImgMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empréstimos || Empréstimos entre Amigos");
        setMinimumSize(new java.awt.Dimension(600, 440));
        setName("telaEmprestimos"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        lblTituloPagina.setFont(new java.awt.Font("Zegoe Light - U", 0, 24)); // NOI18N
        lblTituloPagina.setForeground(new java.awt.Color(254, 254, 254));
        lblTituloPagina.setText("Empréstimos || Empréstimos entre Amigos");
        getContentPane().add(lblTituloPagina);
        lblTituloPagina.setBounds(10, 60, 520, 40);

        tbItens.setFont(new java.awt.Font("Zegoe Light - U", 0, 16)); // NOI18N
        tbItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Campo", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbItens.setEnabled(false);
        tbItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbItensMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbItens);
        if (tbItens.getColumnModel().getColumnCount() > 0) {
            tbItens.getColumnModel().getColumn(0).setResizable(false);
            tbItens.getColumnModel().getColumn(0).setPreferredWidth(5);
            tbItens.getColumnModel().getColumn(1).setResizable(false);
            tbItens.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 110, 370, 270);

        btnEmprestar.setFont(new java.awt.Font("Zegoe Light - U", 0, 18)); // NOI18N
        btnEmprestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/entra64.png"))); // NOI18N
        btnEmprestar.setText("EMPRESTAR");
        btnEmprestar.setActionCommand("");
        btnEmprestar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmprestar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmprestar);
        btnEmprestar.setBounds(10, 130, 150, 130);

        btnDevolver.setFont(new java.awt.Font("Zegoe Light - U", 0, 18)); // NOI18N
        btnDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/sai64.png"))); // NOI18N
        btnDevolver.setText("DEVOLVER");
        btnDevolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDevolver.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnDevolver);
        btnDevolver.setBounds(10, 280, 150, 100);

        btnEmprestados.setFont(new java.awt.Font("Zegoe Light - U", 0, 12)); // NOI18N
        btnEmprestados.setText("Consultar Emprestados");
        btnEmprestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmprestados);
        btnEmprestados.setBounds(10, 260, 150, 20);

        btnDisponiveis.setFont(new java.awt.Font("Zegoe Light - U", 0, 12)); // NOI18N
        btnDisponiveis.setText("Consultar Disponíveis");
        btnDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisponiveisActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisponiveis);
        btnDisponiveis.setBounds(10, 110, 150, 20);

        tbIds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbIds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbIdsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbIds);
        if (tbIds.getColumnModel().getColumnCount() > 0) {
            tbIds.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(170, 110, 40, 240);

        btnMostrar.setFont(new java.awt.Font("Zegoe Light - U", 0, 16)); // NOI18N
        btnMostrar.setText(">");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar);
        btnMostrar.setBounds(170, 350, 40, 30);

        lblImgMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/janela-emprestimos.jpg"))); // NOI18N
        getContentPane().add(lblImgMenu);
        lblImgMenu.setBounds(0, 0, 700, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestarActionPerformed
        // TODO add your handling code here:
        ItemVO ivo = ItemVO.getInstancia();
        ivo.setItemID(evo.getLinhaId());
        
        DatagramSocket conexao;
        
        try 
        {
            String mensagem = "1_8_" + ivo.getItemID() + "_" + lvo.getUser();

            conexao = new DatagramSocket();
            byte[] m = mensagem.getBytes();

            InetAddress aHost = InetAddress.getByName(lvo.getIpServidor());
            int serverPort = 1970;
            
            System.out.println("ENVIOU: " + mensagem);

            DatagramPacket request = new DatagramPacket(m, m.length, aHost, serverPort);
            conexao.send(request);
            
            atualizaDisponiveis();
            atualizaEmprestados();
        } catch (IOException e)
        {  
            System.out.println("IOException: " + e);
        }
    }//GEN-LAST:event_btnEmprestarActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        // TODO add your handling code here:
        ItemVO ivo = ItemVO.getInstancia();
        ivo.setItemID(evo.getLinhaId());
        
        DatagramSocket conexao;
        
        try 
        {
            String mensagem = "9_1_" + ivo.getItemID() + "_" + lvo.getUser();

            conexao = new DatagramSocket();
            byte[] m = mensagem.getBytes();

            InetAddress aHost = InetAddress.getByName(lvo.getIpServidor());
            int serverPort = 1970;
            
            System.out.println("ENVIOU: " + mensagem);

            DatagramPacket request = new DatagramPacket(m, m.length, aHost, serverPort);
            conexao.send(request);
            
            atualizaDisponiveis();
            atualizaEmprestados();
        } catch (IOException e)
        {  
            System.out.println("IOException: " + e);
        }
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void tbItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbItensMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbItensMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void btnEmprestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestadosActionPerformed
        // TODO add your handling code here:
        atualizaEmprestados();
    }//GEN-LAST:event_btnEmprestadosActionPerformed

    private void btnDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisponiveisActionPerformed
        // TODO add your handling code here:
        atualizaDisponiveis();
    }//GEN-LAST:event_btnDisponiveisActionPerformed

    private void tbIdsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbIdsMouseClicked
        // TODO add your handling code here:
        evo.setLinhaId(Integer.parseInt((String) tbIds.getValueAt(tbIds.getSelectedRow(), 0)));
    }//GEN-LAST:event_tbIdsMouseClicked

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        ItemVO ivo = ItemVO.getInstancia();
        ivo.setItemID(evo.getLinhaId());
        
        this.setVisible(false);
        DatagramSocket conexao;
        evo.tableItens.setNumRows(0);
        
        try 
        {
            String mensagem = "2_1_" + ivo.getItemID();

            conexao = new DatagramSocket();
            byte[] m = mensagem.getBytes();

            InetAddress aHost = InetAddress.getByName(lvo.getIpServidor());
            int serverPort = 1970;
            
            System.out.println("ENVIOU: " + mensagem);

            DatagramPacket request = new DatagramPacket(m, m.length, aHost, serverPort);
            conexao.send(request);
            
            this.setVisible(true);
        } catch (IOException e)
        {  
            System.out.println("IOException: " + e);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed
    
    void atualizaDisponiveis() {
        this.setVisible(false);
        DatagramSocket conexao;
        evo.tableIds.setNumRows(0);
        evo.tableItens.setNumRows(0);
        try 
        {
            String mensagem = "9_3_" + lvo.getUser();

            conexao = new DatagramSocket();
            byte[] m = mensagem.getBytes();

            InetAddress aHost = InetAddress.getByName(lvo.getIpServidor());
            int serverPort = 1970;
            
            System.out.println("ENVIOU: " + mensagem);

            DatagramPacket request = new DatagramPacket(m, m.length, aHost, serverPort);
            conexao.send(request);
            
            this.setVisible(true);
        } catch (IOException e)
        {  
            System.out.println("IOException: " + e);
        }
    }
    
    void atualizaEmprestados() {
        this.setVisible(false);
        DatagramSocket conexao;
        evo.tableIds.setNumRows(0);
        evo.tableItens.setNumRows(0);
        try 
        {
            String mensagem = "1_9_" + lvo.getUser();

            conexao = new DatagramSocket();
            byte[] m = mensagem.getBytes();

            InetAddress aHost = InetAddress.getByName(lvo.getIpServidor());
            int serverPort = 1970;
            
            System.out.println("ENVIOU: " + mensagem);

            DatagramPacket request = new DatagramPacket(m, m.length, aHost, serverPort);
            conexao.send(request);
            
            this.setVisible(true);
        } catch (IOException e)
        {  
            System.out.println("IOException: " + e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaGerenciarUsuarios().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnDisponiveis;
    private javax.swing.JButton btnEmprestados;
    private javax.swing.JButton btnEmprestar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblImgMenu;
    private javax.swing.JLabel lblTituloPagina;
    private javax.swing.JTable tbIds;
    private javax.swing.JTable tbItens;
    // End of variables declaration//GEN-END:variables
}
