/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Emprestimos.Telas;

import Emprestimos.VO.ConnectionAmigos;
import Emprestimos.VO.ConnectionAmigos2;
import Emprestimos.VO.LoginVO;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;

/**
 *
 * @author lennonalves
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form LoginUsuario
     */
    
    public static TelaLogin instancia;
    
    protected TelaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public static TelaLogin getInstancia() {
        if (instancia == null)
            instancia = new TelaLogin();
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSenha = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        txtServidor = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        lblServidor = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblTelaLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login || Empréstimos entre Amigos");
        setMinimumSize(new java.awt.Dimension(276, 310));
        setName("telaLogin"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        lblSenha.setFont(new java.awt.Font("Zegoe Light - U", 0, 12)); // NOI18N
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(40, 160, 40, 16);

        lblLogin.setFont(new java.awt.Font("Zegoe Light - U", 0, 14)); // NOI18N
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("Seja Bem Vindo!");
        getContentPane().add(lblLogin);
        lblLogin.setBounds(40, 90, 190, 30);

        lblUsuario.setFont(new java.awt.Font("Zegoe Light - U", 0, 12)); // NOI18N
        lblUsuario.setText("Usuário:");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(40, 130, 50, 16);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(90, 150, 140, 30);

        txtServidor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtServidor.setText("localhost");
        getContentPane().add(txtServidor);
        txtServidor.setBounds(50, 200, 180, 30);

        btnEntrar.setFont(new java.awt.Font("Zegoe Light - U", 0, 14)); // NOI18N
        btnEntrar.setText("ENTRAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(50, 230, 180, 20);

        lblServidor.setFont(new java.awt.Font("Zegoe Light - U", 0, 12)); // NOI18N
        lblServidor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServidor.setText("IP do Servidor:");
        lblServidor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblServidor);
        lblServidor.setBounds(50, 180, 180, 16);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(90, 120, 140, 30);

        lblTelaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/login-emprestimos.jpg"))); // NOI18N
        getContentPane().add(lblTelaLogin);
        lblTelaLogin.setBounds(0, 0, 280, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        LoginVO lvo = LoginVO.getInstancia();
        lvo.setStatus(false);
        lvo.setUser(txtUsuario.getText());
        lvo.setSenha(txtSenha.getText());
        lvo.setIpServidor(txtServidor.getText());
        
        DatagramSocket conexao;

        try 
        {
            String mensagem = "1_1_" + lvo.getUser() + "_" + lvo.getSenha();

            conexao = new DatagramSocket();
            byte[] m = mensagem.getBytes();

            InetAddress aHost = InetAddress.getByName(lvo.getIpServidor());
            int serverPort = 1970;
            
            System.out.println("ENVIOU: " + mensagem);

            DatagramPacket request = new DatagramPacket(m, m.length, aHost, serverPort);
            conexao.send(request);
            
//            ConnectionAmigos ca = new ConnectionAmigos();
//            ca.start();
            
            String porta = Integer.toString(conexao.getPort());
            ConnectionAmigos2 ca = new ConnectionAmigos2(porta, conexao);
            ca.start();
            
            this.dispose();
        } catch (IOException e)
        {  
            System.out.println("IOException: " + e);
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblServidor;
    private javax.swing.JLabel lblTelaLogin;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtServidor;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
