/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Emprestimos.Telas;

import Emprestimos.RN.ConsultaRN;
import Emprestimos.VO.ConsultaVO;
import Emprestimos.VO.ItemVO;
import Emprestimos.VO.LoginVO;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lennonalves
 */
public class TelaConsultaItens extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    
    public static TelaConsultaItens instancia;
    
    protected TelaConsultaItens() {
        initComponents();
        this.setLocationRelativeTo(null);
        cvo.tableIds = (DefaultTableModel) tbIds.getModel();
        cvo.tableItens = (DefaultTableModel) tbItens.getModel();
    }
    
    public static TelaConsultaItens getInstancia() {
        if (instancia == null)
            instancia = new TelaConsultaItens();
        return instancia;
    }
    
    ConsultaVO cvo = ConsultaVO.getInstancia();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    LoginVO lvo = LoginVO.getInstancia();
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        lblNome = new javax.swing.JLabel();
        lblTituloPagina = new javax.swing.JLabel();
        cbOpcoes = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIds = new javax.swing.JTable();
        lblPesquisarPor = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        btnIr = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbItens = new javax.swing.JTable();
        btnEnviar = new javax.swing.JButton();
        lblImgMenu = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jTextPane1);

        lblNome.setFont(new java.awt.Font("Zegoe Light - U", 0, 14)); // NOI18N
        lblNome.setText("Nome:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Itens || Empréstimos entre Amigos");
        setMinimumSize(new java.awt.Dimension(600, 440));
        setName("telaConsultarItens"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        lblTituloPagina.setFont(new java.awt.Font("Zegoe Light - U", 0, 24)); // NOI18N
        lblTituloPagina.setForeground(new java.awt.Color(254, 254, 254));
        lblTituloPagina.setText("Consultar Itens || Empréstimos entre Amigos");
        getContentPane().add(lblTituloPagina);
        lblTituloPagina.setBounds(10, 60, 580, 40);

        cbOpcoes.setFont(new java.awt.Font("Zegoe Light - U", 0, 16)); // NOI18N
        cbOpcoes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Meus Itens", "Itens dos Amigos" }));
        cbOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOpcoesActionPerformed(evt);
            }
        });
        getContentPane().add(cbOpcoes);
        cbOpcoes.setBounds(110, 110, 400, 30);

        tbIds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbIds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbIdsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbIds);
        if (tbIds.getColumnModel().getColumnCount() > 0) {
            tbIds.getColumnModel().getColumn(0).setResizable(false);
            tbIds.getColumnModel().getColumn(0).setHeaderValue("ID");
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 40, 190);

        lblPesquisarPor.setFont(new java.awt.Font("Zegoe Light - U", 0, 14)); // NOI18N
        lblPesquisarPor.setText("Pesquisar por:");
        getContentPane().add(lblPesquisarPor);
        lblPesquisarPor.setBounds(20, 110, 90, 30);

        btnMostrar.setFont(new java.awt.Font("Zegoe Light - U", 0, 16)); // NOI18N
        btnMostrar.setText(">");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar);
        btnMostrar.setBounds(20, 330, 40, 30);

        btnIr.setFont(new java.awt.Font("Zegoe Light - U", 0, 16)); // NOI18N
        btnIr.setText("IR");
        btnIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrActionPerformed(evt);
            }
        });
        getContentPane().add(btnIr);
        btnIr.setBounds(520, 110, 60, 30);

        tbItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Campo", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbItens.setEnabled(false);
        tbItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbItensMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbItens);
        if (tbItens.getColumnModel().getColumnCount() > 0) {
            tbItens.getColumnModel().getColumn(0).setResizable(false);
            tbItens.getColumnModel().getColumn(1).setResizable(false);
            tbItens.getColumnModel().getColumn(1).setPreferredWidth(350);
        }

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(72, 140, 510, 220);

        btnEnviar.setFont(new java.awt.Font("Zegoe Light - U", 0, 16)); // NOI18N
        btnEnviar.setText("ENVIAR");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(480, 360, 100, 30);

        lblImgMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/janela-emprestimos.jpg"))); // NOI18N
        getContentPane().add(lblImgMenu);
        lblImgMenu.setBounds(0, 0, 700, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOpcoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOpcoesActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        listarItens(lvo);
    }//GEN-LAST:event_formWindowActivated

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        ItemVO ivo = ItemVO.getInstancia();
        ivo.setItemID(cvo.getLinhaId());
        
        this.setVisible(false);
        DatagramSocket conexao;
        cvo.tableItens.setNumRows(0);
        
        try 
        {
            String mensagem = "2_1_" + ivo.getItemID();

            conexao = new DatagramSocket();
            byte[] m = mensagem.getBytes();

            InetAddress aHost = InetAddress.getByName(lvo.getIpServidor());
            int serverPort = 1970;
            
            System.out.println("ENVIOU: " + mensagem);

            DatagramPacket request = new DatagramPacket(m, m.length, aHost, serverPort);
            conexao.send(request);
            
            this.setVisible(true);
        } catch (IOException e)
        {  
            System.out.println("IOException: " + e);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        DatagramSocket conexao;
        cvo.tableIds.setNumRows(0);
        cvo.tableItens.setNumRows(0);
        
        if (cbOpcoes.getSelectedIndex() == 0) {
            try 
            {
                String mensagem = "1_6_" + lvo.getUser();

                conexao = new DatagramSocket();
                byte[] m = mensagem.getBytes();

                InetAddress aHost = InetAddress.getByName(lvo.getIpServidor());
                int serverPort = 1970;
                
                System.out.println("ENVIOU: " + mensagem);

                DatagramPacket request = new DatagramPacket(m, m.length, aHost, serverPort);
                conexao.send(request);
                
                this.setVisible(true);
            } catch (IOException e)
            {  
                System.out.println("IOException: " + e);
            }
        }
        
        if (cbOpcoes.getSelectedIndex() == 1) {
            try 
            {
                String mensagem = "1_7_" + lvo.getUser();

                conexao = new DatagramSocket();
                byte[] m = mensagem.getBytes();

                InetAddress aHost = InetAddress.getByName(lvo.getIpServidor());
                int serverPort = 1970;
                
                System.out.println("ENVIOU: " + mensagem);

                DatagramPacket request = new DatagramPacket(m, m.length, aHost, serverPort);
                conexao.send(request);
                
                this.setVisible(true);
            } catch (IOException e)
            {  
                System.out.println("IOException: " + e);
            }
        }
    }//GEN-LAST:event_btnIrActionPerformed

    private void tbIdsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbIdsMouseClicked
        // TODO add your handling code here:
        cvo.setLinhaId(Integer.parseInt((String) tbIds.getValueAt(tbIds.getSelectedRow(), 0)));
    }//GEN-LAST:event_tbIdsMouseClicked

    private void tbItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbItensMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbItensMouseClicked

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        ItemVO ivo = ItemVO.getInstancia();
        ivo.setItemID(cvo.getLinhaId());
        ConsultaRN crn = ConsultaRN.getInstancia();
        
        TelaGerenciarItens tgi = TelaGerenciarItens.getInstancia();
        tgi.preencheCampos(crn.preencheCampos(ivo.getItemID()));
        
        this.setVisible(false);
        tgi.setVisible(true);
    }//GEN-LAST:event_btnEnviarActionPerformed

    void listarItens (LoginVO lvo) {
        if (cvo.isFlag() == true) { /* veio do gerenciar itens */
            cbOpcoes.setEnabled(false); btnIr.setEnabled(false); btnEnviar.setEnabled(true); btnMostrar.setEnabled(true);
            cvo.tableIds.setNumRows(0);
            
            ConsultaRN crn = ConsultaRN.getInstancia();
            String mensagem = crn.consultaMeus(lvo.getUser()).substring(4); /* consulta id's meus itens */
            String[] corte = mensagem.split("_");
            
            for (int i = 0; i < (corte.length); i++) {
                cvo.tableIds.addRow(new String [] {corte[i]});
            }
        } else { /* veio do menu */
            cbOpcoes.setEnabled(true); btnIr.setEnabled(true); btnEnviar.setEnabled(false); btnMostrar.setEnabled(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaGerenciarUsuarios().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnIr;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox cbOpcoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblImgMenu;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPesquisarPor;
    private javax.swing.JLabel lblTituloPagina;
    private javax.swing.JTable tbIds;
    private javax.swing.JTable tbItens;
    // End of variables declaration//GEN-END:variables

}
