/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Exercicios;

import java.util.Scanner;

/**
 *
 * @author lennonalves
 */
public class TelaClienteServidor extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    public TelaClienteServidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMensagem1 = new javax.swing.JTextField();
        lblMensagem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtResposta = new javax.swing.JTextField();
        txtMensagem2 = new javax.swing.JTextField();
        lblMensagem1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnCli1 = new javax.swing.JButton();
        BtnOk1 = new javax.swing.JButton();
        BtnCli2 = new javax.swing.JButton();
        BtnOk3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(740, 300));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cantarell", 2, 36)); // NOI18N
        jLabel1.setText("CLIENTE 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 20, 200, 50);
        getContentPane().add(txtMensagem1);
        txtMensagem1.setBounds(30, 100, 320, 28);

        lblMensagem.setText("Mensagem:");
        getContentPane().add(lblMensagem);
        lblMensagem.setBounds(30, 80, 90, 16);

        jLabel2.setText("Resposta do Servidor:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 200, 170, 16);

        txtResposta.setEnabled(false);
        getContentPane().add(txtResposta);
        txtResposta.setBounds(30, 220, 680, 28);
        getContentPane().add(txtMensagem2);
        txtMensagem2.setBounds(390, 100, 320, 28);

        lblMensagem1.setText("Mensagem:");
        getContentPane().add(lblMensagem1);
        lblMensagem1.setBounds(390, 80, 90, 16);

        jLabel3.setFont(new java.awt.Font("Cantarell", 2, 36)); // NOI18N
        jLabel3.setText("CLIENTE 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 20, 200, 50);

        BtnCli1.setText("ENVIAR");
        BtnCli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCli1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCli1);
        BtnCli1.setBounds(30, 150, 320, 28);

        BtnOk1.setText("ENVIAR");
        getContentPane().add(BtnOk1);
        BtnOk1.setBounds(30, 150, 320, 28);

        BtnCli2.setText("ENVIAR");
        BtnCli2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCli2ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCli2);
        BtnCli2.setBounds(390, 150, 320, 28);

        BtnOk3.setText("ENVIAR");
        getContentPane().add(BtnOk3);
        BtnOk3.setBounds(390, 150, 320, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCli1ActionPerformed
        // TODO add your handling code here:
        Mensagem m = new Mensagem();
        m.setPalavra(txtMensagem1.getText());
        
        Servidor serv = new Servidor();
        serv.modifica();
        
        txtResposta.setText(m.getPalavra());
    }//GEN-LAST:event_BtnCli1ActionPerformed

    private void BtnCli2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCli2ActionPerformed
        // TODO add your handling code here:
        Mensagem m = new Mensagem();
        m.setPalavra(txtMensagem2.getText());
        
        Servidor serv = new Servidor();
        serv.modifica();
        
        txtResposta.setText(m.getPalavra());
    }//GEN-LAST:event_BtnCli2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClienteServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClienteServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClienteServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClienteServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClienteServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCli1;
    private javax.swing.JButton BtnCli2;
    private javax.swing.JButton BtnOk1;
    private javax.swing.JButton BtnOk3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblMensagem1;
    private javax.swing.JTextField txtMensagem1;
    private javax.swing.JTextField txtMensagem2;
    private javax.swing.JTextField txtResposta;
    // End of variables declaration//GEN-END:variables
}
