/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Exercicios;

/**
 *
 * @author lennonalves
 */
public class TelaServidor extends javax.swing.JFrame {

    public static TelaServidor instancia;
    
    public static TelaServidor getInstancia()
    {
        if (instancia == null)
            instancia = new TelaServidor();
        return instancia;
    }
    
    /**
     * @return the comunica
     */
    public static String getComunica() {
        return comunica;
    }

    /**
     * @param aComunica the comunica to set
     */
    public static void setComunica(String aComunica) {
        comunica = aComunica;
    }

    /**
     * @return the comunica
     */

    /**
     * Creates new form TelaServidor
     */
    private TelaServidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblResposta = new javax.swing.JLabel();
        txtResposta = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 180));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        lblTitle.setFont(new java.awt.Font("Cantarell", 2, 36)); // NOI18N
        lblTitle.setText("SERVIDOR");
        lblTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTitleMouseClicked(evt);
            }
        });
        getContentPane().add(lblTitle);
        lblTitle.setBounds(100, 10, 210, 50);

        lblResposta.setText("Resposta do Servidor:");
        getContentPane().add(lblResposta);
        lblResposta.setBounds(30, 70, 160, 16);

        txtResposta.setEnabled(false);
        getContentPane().add(txtResposta);
        txtResposta.setBounds(30, 90, 340, 28);

        btnAtualizar.setText("F5");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(320, 20, 50, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static String comunica;
    private static String novaMensagem;
    
    void modifica()
    {
        setComunica(getComunica().toUpperCase());
        System.out.println("get: " + getComunica());
        System.out.println("nova mensagem (1): " + TelaServidor.novaMensagem);
        TelaServidor.novaMensagem = getComunica();
        System.out.println("nova mensagem (2): " + TelaServidor.novaMensagem);
        preencher(TelaServidor.novaMensagem);
    }
    
    void preencher(String msg)
    {
        txtResposta.setText("carregando...");
        txtResposta.setText(msg);
        System.out.println("msg: " + msg);
    }
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void lblTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTitleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTitleMouseClicked

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        preencher(getComunica());
        //txtResposta.setText(getComunica());
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaServidor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JLabel lblResposta;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtResposta;
    // End of variables declaration//GEN-END:variables

}
