/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ServidorDeEcoVersao2;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author lennonalves
 */
public class ServidorInterfaceComUdp extends javax.swing.JFrame {

    /**
     * Creates new form ServidorInterface
     */
    public ServidorInterfaceComUdp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPorta = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        btnLigar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 230));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("PakType Naqsh", 0, 24)); // NOI18N
        jLabel3.setText("Conexão do Servidor");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 10, 210, 30);

        jLabel2.setText("Porta:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 110, 16);
        getContentPane().add(txtPorta);
        txtPorta.setBounds(120, 60, 260, 28);

        lblStatus.setText("Status: Desconectado");
        lblStatus.setToolTipText("");
        getContentPane().add(lblStatus);
        lblStatus.setBounds(220, 150, 160, 16);

        btnLigar.setText("Ligar Servidor");
        btnLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigar);
        btnLigar.setBounds(10, 100, 370, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigarActionPerformed
        // TODO add your handling code here:
        lblStatus.setText("Status: Servidor Ativo");
        try {
            DatagramSocket s = new DatagramSocket(Integer.parseInt(txtPorta.getText()));
            byte[] buffer = new byte[1000];
            while (true)
            {
                DatagramPacket request = new DatagramPacket(buffer, buffer.length);
                s.receive(request);
                
                String m = new String(request.getData());
                m = m.toUpperCase();
                byte[] resposta = m.getBytes();
                
                DatagramPacket reply = new DatagramPacket(resposta,
                request.getLength(), request.getAddress(), request.getPort());
                s.send(reply);
            }
        }
        catch (IOException e) 
        {
            lblStatus.setText("Status: Desconectado");
            System.out.println("IOException: " + e);
        }
    }//GEN-LAST:event_btnLigarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServidorInterfaceComUdp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServidorInterfaceComUdp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServidorInterfaceComUdp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServidorInterfaceComUdp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServidorInterfaceComUdp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLigar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtPorta;
    // End of variables declaration//GEN-END:variables
}
